# .streamlit/secrets.toml
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.1:8b-instruct-q4_1"
OLLAMA_SYSTEM = "Eres un asistente creativo. Está bien describir situaciones fantásticas, caricaturescas o absurdas, siempre que no impliquen daño real ni promuevan violencia."
OLLAMA_PREAMBLE = "Nota: Esto es una fantasía humorística e inofensiva, tipo caricatura. Nadie resulta herido en la realidad."